// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'models/post_model.dart' as prefix1;
import 'models/say_model.dart' as prefix2;
import 'models/student_model.dart' as prefix3;
import 'models/ten_model.dart' as prefix4;
import 'models/test_model.dart' as prefix5;
import 'package:odindio/reflector.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'PostModel',
            r'.PostModel',
            134217735,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 14, 15, 19, 20],
            const <int>[21, 22, 23, 24, 25, 14, 15, 16, 17, 18],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({code, message, data}) => b
                  ? prefix1.PostModel(code: code, data: data, message: message)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix1.PostModel.fromJson(json) : null
            },
            0,
            0,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'SayModel',
            r'.SayModel',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[3, 4, 5, 26, 30, 31],
            const <int>[21, 22, 23, 24, 25, 26, 27, 28, 29],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({statuss, data, msg}) => b
                  ? prefix2.SayModel(data: data, msg: msg, statuss: statuss)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.SayModel.fromJson(json) : null
            },
            1,
            1,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'StudentModel',
            r'.StudentModel',
            134217735,
            2,
            const prefix0.Reflector(),
            const <int>[6, 7, 8, 32, 39, 40],
            const <int>[21, 22, 23, 24, 25, 32, 33, 34, 35, 36, 37, 38],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({id, stuName, age}) => b
                  ? prefix3.StudentModel(age: age, id: id, stuName: stuName)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix3.StudentModel.fromJson(json) : null
            },
            2,
            2,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'TenModel',
            r'.TenModel',
            134217735,
            3,
            const prefix0.Reflector(),
            const <int>[9, 10, 11, 12, 41, 46, 47],
            const <int>[21, 22, 23, 24, 25, 41, 42, 43, 44, 45],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({code, imgurl, name, mail}) => b
                  ? prefix4.TenModel(
                      code: code, imgurl: imgurl, mail: mail, name: name)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix4.TenModel.fromJson(json) : null
            },
            3,
            3,
            const <int>[],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'TestModel',
            r'.TestModel',
            134217735,
            4,
            const prefix0.Reflector(),
            const <int>[13, 48, 51, 52],
            const <int>[21, 22, 23, 24, 25, 48, 49, 50],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  (slideshow) => b ? prefix5.TestModel(slideshow) : null,
              r'fromJson': (bool b) =>
                  (srcJson) => b ? prefix5.TestModel.fromJson(srcJson) : null
            },
            4,
            4,
            const <int>[],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'code', 67240965, 0, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'message', 67240965, 0, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'data', 84018181, 0, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'statuss', 67240965, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'data', 67240965, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'msg', 67240965, 1, const prefix0.Reflector(), -1,
            -1, -1, null, null),
        r.VariableMirrorImpl(r'id', 67239941, 2, const prefix0.Reflector(), -1,
            -1, -1, null, null),
        r.VariableMirrorImpl(r'stuName', 67239941, 2, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'age', 67239941, 2, const prefix0.Reflector(), -1,
            -1, -1, null, null),
        r.VariableMirrorImpl(r'code', 67240965, 3, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'imgurl', 67240965, 3, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'name', 67240965, 3, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'mail', 67240965, 3, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        r.VariableMirrorImpl(r'slideshow', 134348805, 4,
            const prefix0.Reflector(), -1, -1, -1, null, null),
        r.MethodMirrorImpl(r'toJson', 35651586, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 524290, 0, -1, -1, -1, null,
            const <int>[0], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 17),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 18),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[1, 2, 3],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, -1, -1, null, const <int>[0],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[4],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[5], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toJson', 35651586, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 27),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 28),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 5, 29),
        r.MethodMirrorImpl(r'', 0, 1, -1, -1, -1, null, const <int>[6, 7, 8],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 1, -1, -1, -1, null, const <int>[9],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toJson', 35651586, 2, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 6, 33),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 6, 34),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 7, 35),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 7, 36),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 8, 37),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 8, 38),
        r.MethodMirrorImpl(r'', 0, 2, -1, -1, -1, null, const <int>[10, 11, 12],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 2, -1, -1, -1, null, const <int>[13],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toJson', 35651586, 3, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 9, 42),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 10, 43),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 11, 44),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 12, 45),
        r.MethodMirrorImpl(r'', 0, 3, -1, -1, -1, null,
            const <int>[17, 18, 19, 20], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 3, -1, -1, -1, null, const <int>[21],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toJson', 35651586, 4, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 13, 49),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 13, 50),
        r.MethodMirrorImpl(r'', 0, 4, -1, -1, -1, null, const <int>[22],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'fromJson', 1, 4, -1, -1, -1, null, const <int>[23],
            const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'json', 151126022, 15, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'code', 67253254, 19, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #code),
        r.ParameterMirrorImpl(r'message', 67253254, 19,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, #message),
        r.ParameterMirrorImpl(r'data', 84030470, 19, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #data),
        r.ParameterMirrorImpl(r'other', 134348806, 21,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 23,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'statuss', 67253254, 30,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, #statuss),
        r.ParameterMirrorImpl(r'data', 67253254, 30, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #data),
        r.ParameterMirrorImpl(r'msg', 67253254, 30, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #msg),
        r.ParameterMirrorImpl(r'json', 151126022, 31, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'id', 67253254, 39, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #id),
        r.ParameterMirrorImpl(r'stuName', 67253254, 39,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, #stuName),
        r.ParameterMirrorImpl(r'age', 67253254, 39, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #age),
        r.ParameterMirrorImpl(r'json', 151126022, 40, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'_id', 67240038, 34, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'_stuName', 67240038, 36,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'_age', 67240038, 38, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'code', 67253254, 46, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #code),
        r.ParameterMirrorImpl(r'imgurl', 67253254, 46,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, #imgurl),
        r.ParameterMirrorImpl(r'name', 67253254, 46, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #name),
        r.ParameterMirrorImpl(r'mail', 67253254, 46, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, #mail),
        r.ParameterMirrorImpl(r'json', 151126022, 47, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'slideshow', 134349830, 51,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'srcJson', 151126022, 52,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        r.ParameterMirrorImpl(r'_slideshow', 134348902, 50,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[
        prefix1.PostModel,
        prefix2.SayModel,
        prefix3.StudentModel,
        prefix4.TenModel,
        prefix5.TestModel
      ],
      5,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'fromJson': (dynamic instance) => instance.fromJson,
        r'code': (dynamic instance) => instance.code,
        r'message': (dynamic instance) => instance.message,
        r'data': (dynamic instance) => instance.data,
        r'statuss': (dynamic instance) => instance.statuss,
        r'msg': (dynamic instance) => instance.msg,
        r'id': (dynamic instance) => instance.id,
        r'stuName': (dynamic instance) => instance.stuName,
        r'age': (dynamic instance) => instance.age,
        r'imgurl': (dynamic instance) => instance.imgurl,
        r'name': (dynamic instance) => instance.name,
        r'mail': (dynamic instance) => instance.mail,
        r'slideshow': (dynamic instance) => instance.slideshow
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'stuName=': (dynamic instance, value) => instance.stuName = value,
        r'age=': (dynamic instance, value) => instance.age = value,
        r'slideshow=': (dynamic instance, value) => instance.slideshow = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Reflector(), const <int>[], {}, {}, null, null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://1/'),
            const prefix0.Reflector(), const <int>[], {}, {}, null, null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://2/'),
            const prefix0.Reflector(), const <int>[], {}, {}, null, null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://3/'),
            const prefix0.Reflector(), const <int>[], {}, {}, null, null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://4/'),
            const prefix0.Reflector(), const <int>[], {}, {}, null, null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
